### ISSUE TITLE
마이페이지 화면 구현 

### ISSUE THREAD

**Issue by shjthd92** [codestates/newDe#18]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ] 유저 정보 받아와서 렌더링
2. [ ] 유저가 쓴 글 정보 받아와서 렌더링 
3. [ ] 회원정보 수정, 회원탈퇴 기능과 이어지도록 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
