### ISSUE TITLE
테스트 알고리즘 만들기 및 테스트 페이지 구현 

### ISSUE THREAD

**Issue by shjthd92** [codestates/newDe#20]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ] 설문조사의 항목과 설문된 내용을 바탕으로 어떻게 결과를 낼건지 고려 
2. [ ] 적절한 문항 만들기 
3. [ ] 테스트 페이지는 이후 자연스럽게 게시판으로 유도되도록 만들기 

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
