### ISSUE TITLE
글 및 댓글 쓰기와 수정 기능 구현 

### ISSUE THREAD

**Issue by shjthd92** [codestates/newDe#26]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ] 글쓰기 기능 구현 
2. [ ] 댓글 쓰기 기능 구현 
3. [ ] 글수정, 댓글 수정기능 구현 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
