### ISSUE TITLE
SR-사이트맵, 유저플로우, 와이어프레임 작성 

### ISSUE THREAD

**Issue by shjthd92** [codestates/newDe#3]
### ISSUE
- Group:  `sr`
- Type: `planning`
- Detail: `draw wireframe`

### TODO
1. [ ] 사이트의 구조를 개략적으로 그려보는 사이트맵 작성
2. [ ] 사용자가 앱을 사용하는 구조인 유저플로우 작성
3. [ ] 사이트맵, 유저플로우를 바탕으로 와이어프레임 짜보기 

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `sr`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
