### ISSUE TITLE
SR-Prototype 작성

### ISSUE THREAD

**Issue by shjthd92** [codestates/newDe#4]
### ISSUE
- Group:  `sr`
- Type: `planning`
- Detail: draw prototype

### TODO
1. [ ] 각 페이지의 세부적인 디자인 결정 
2. [ ] 각 페이지가 어떻게 상호작용을 하는지 oven 을 이용하여 구현 
3. [ ] 각자 만들어본 프로토타입을 바탕으로 가장 나은 디자인 결정하기 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `sr`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
