### ISSUE TITLE
SR-Data Schema 작성 

### ISSUE THREAD

**Issue by shjthd92** [codestates/newDe#5]
### ISSUE
- Group:  `sr`
- Type: `planning`
- Detail: data schema

### TODO
1. [ ] 게시판 서비스를 위해 어떤 정보를 데이터베이스에 저장해야 하는지 정하기 
2. [ ] 각각의 테이블이 어떤 항목을 중심으로 관계를 맺고 있는지 고찰하여 각 테이블의 관계 설정하기 
3. [ ] 불필요한 항목이 있지는 않은지 확인해보기 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1.5h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
