### ISSUE TITLE
SR-API 문서 작성 

### ISSUE THREAD

**Issue by shjthd92** [codestates/newDe#6]
### ISSUE
- Group:  `sr`
- Type: `planning`
- Detail: for rest api 

### TODO
1. [ ] 클라이언트와 서버가 어떤 기능에서 통신을 주고 받는지 확인하고 해당 통신에 적합한 endpoint 이름 설정
2. [ ] 각각의 요청-응답이 어떤 구조로 데이터를 주고 받는지 설정하기 
3. [ ] 부적합한 방식으로 작성된 부분이 있는지 검토하기 

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
