### ISSUE TITLE
To Do List 작성 및 Not To Do List 확인 

### ISSUE THREAD

**Issue by shjthd92** [codestates/newDe#9]
### ISSUE
- Group:  `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ] To Do List Bare Minimum 작성 
2. [ ] To Do List Advanced & Nightmare 구현거리 정하기 
3. [ ] Not To do 점검 

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
